name: Build MiniTVRenamer MSI (Python + WiX)

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        shell: pwsh
        run: |
          pyinstaller app/main.py --name MiniTVRenamer --noconfirm --windowed --onefile --icon app/icon.ico

      - name: Install WiX Toolset
        shell: pwsh
        run: |
          choco install wixtoolset -y
          echo "C:\Program Files (x86)\WiX Toolset v3.14\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Build MSI
        shell: pwsh
        run: |
          heat dir dist -gg -sreg -sfrag -srd -dr INSTALLFOLDER -cg AppComponents -out wix\HarvestedFiles.wxs
          candle wix\Product.wxs wix\HarvestedFiles.wxs -out wix\
          light wix\Product.wixobj wix\HarvestedFiles.wixobj -ext WixUIExtension -cultures:en-us -out MiniTVRenamer.msi

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiniTVRenamer-Installer
          path: MiniTVRenamer.msi

