- name: Write WiX authoring
  shell: bash
  run: |
    mkdir -p installer
    cat > installer/MiniFileBot.wxs <<'WXS'
    <?xml version="1.0" encoding="UTF-8"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
      <Product Id="*"
               Name="MiniFileBot"
               Language="1033"
               Version="$(var.ProductVersion)"
               Manufacturer="MiniFileBot"
               UpgradeCode="A4E6F40E-8BB0-4410-9C91-6B8B0A9D21E0">
        <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine" />
        <MediaTemplate EmbedCab="yes" CompressionLevel="high" />
        <MajorUpgrade AllowDowngrades="no"
                      DowngradeErrorMessage="A newer version of MiniFileBot is already installed." />

        <Property Id="WIXUI_INSTALLDIR" Value="INSTALLFOLDER" />
        <UIRef Id="WixUI_InstallDir" />
        <UIRef Id="WixUI_ErrorProgressText" />

        <Directory Id="TARGETDIR" Name="SourceDir">
          <Directory Id="ProgramFilesFolder">
            <Directory Id="INSTALLFOLDER" Name="MiniFileBot" />
          </Directory>
          <Directory Id="ProgramMenuFolder" />
        </Directory>

        <!-- Start menu shortcut with HKLM KeyPath (avoids ICE03) -->
        <DirectoryRef Id="ProgramMenuFolder">
          <Component Id="ProgramMenuShortcuts" Guid="*">
            <Shortcut Id="StartMenuShortcut"
                      Name="MiniFileBot"
                      Target="[INSTALLFOLDER]MiniFileBot.exe"
                      WorkingDirectory="INSTALLFOLDER" />
            <RemoveFolder Id="RemovePMF" Directory="ProgramMenuFolder" On="uninstall" />
            <RegistryValue Root="HKLM"
                           Key="Software\\MiniFileBot"
                           Name="Installed"
                           Type="integer"
                           Value="1"
                           KeyPath="yes" />
          </Component>
        </DirectoryRef>

        <ComponentGroup Id="AppFiles" Directory="INSTALLFOLDER">
          <Component Id="ExeCmp" Guid="*">
            <File Id="AppExe" Source="$(var.BuildOut)\MiniFileBot.exe" KeyPath="yes" />
          </Component>
          <Component Id="CfgCmp" Guid="*">
            <File Id="Cfg" Source="$(var.BuildOut)\config.yaml" />
          </Component>
        </ComponentGroup>

        <Feature Id="MainFeature" Title="MiniFileBot" Level="1">
          <ComponentGroupRef Id="AppFiles" />
          <ComponentRef Id="ProgramMenuShortcuts" />
        </Feature>
      </Product>
    </Wix>
    WXS











